[defaults]
node_name                   = "right_arm"
use_node_name_as_topic_base = true
update_rate_hz              = 100.0

# Sim back-end
sim_joint_states_topic = "/joint_states"
sim_controller_topic   = "/right_arm_controller/joint_trajectory"
trajectory_time_sec    = 0.05

[SpR]
joint_limit_min  = -1.570796
joint_limit_max  =  0.017453
motor_homing_pos =  0.0

[SrR]
joint_limit_min  = -0.610865
joint_limit_max  =  0.087266
motor_homing_pos =  0.0

[SwR]
joint_limit_min  = -1.570796
joint_limit_max  =  0.017453
motor_homing_pos =  0.0

[EpR]
joint_limit_min  = -0.017453
joint_limit_max  =  2.094395
motor_homing_pos =  0.0

[WwR]
joint_limit_min  = -2.356194
joint_limit_max  =  0.785398
motor_homing_pos =  0.0

[WpR]
joint_limit_min  = -0.785398
joint_limit_max  =  0.785398
motor_homing_pos =  0.0

[WrR]
joint_limit_min  = -0.785398
joint_limit_max  =  0.785398
motor_homing_pos =  0.0
